---
- name: Obtener informacion de maquina virtual en VMWare
  community.vmware.vmware_vm_info:
    hostname: '{{ lookup("ansible.builtin.env", "VMWARE_HOST") }}'
    username: '{{ lookup("ansible.builtin.env", "VMWARE_USER") }}'
    password: '{{ lookup("ansible.builtin.env", "VMWARE_PASSWORD") }}'
    vm_name: "{{ nombre_server }}"
    validate_certs: false
  delegate_to: localhost
  register: registro_informacion_vmware
  changed_when: false

- name: Generar snapshot de maquina virtual en VMWare
  community.vmware.vmware_guest_snapshot:
    hostname: '{{ lookup("ansible.builtin.env", "VMWARE_HOST") }}'
    username: '{{ lookup("ansible.builtin.env", "VMWARE_USER") }}'
    password: '{{ lookup("ansible.builtin.env", "VMWARE_PASSWORD") }}'
    datacenter: "{{ registro_informacion_vmware['virtual_machines'][0]['datacenter'] }}"
    folder: "{{ registro_informacion_vmware['virtual_machines'][0]['folder'] }}"
    name: "{{ nombre_server }}"
    state: present
    snapshot_name: "snapshot_jobID-{{ lookup('ansible.builtin.env', 'JOB_ID') | int }}_{{ ansible_date_time['date'] }}"
    validate_certs: false
    quiesce: "{{ create_snapshot_quiesce }}"
  delegate_to: localhost
  register: registro_snapshot
...
