---
- name: Obtener informacion de maquina virtual en VMWare
  community.vmware.vmware_vm_info:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    vm_name: "{{ nombre_server }}"
    validate_certs: false
  delegate_to: localhost
  register: registro_informacion_vmware
  changed_when: false

# - name: Validar que la máquina virtual existe
#   ansible.builtin.assert:
#     that:
#       -
#     fail_msg: "La máquina virtual {{ nombre_server }} no existe en VMware."
#     quiet: true

- name: Generar snapshot de maquina virtual en VMWare
  community.vmware.vmware_guest_snapshot:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    datacenter: "{{ registro_informacion_vmware.virtual_machines.0.datacenter }}"
    folder: "{{ registro_informacion_vmware.virtual_machines.0.folder }}"
    name: "{{ nombre_server }}"
    state: present
    snapshot_name: "snapshot_jobID-{{ tower_job_id }}{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
    validate_certs: false
  delegate_to: localhost
  register: registro_snapshot
  ignore_errors: true
...
